include: package:very_good_analysis/analysis_options.3.0.1.yaml

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false

analyzer:
    exclude: 
      - '**/*_generated.dart'
      - '**/*_freezed.dart'
      - '**/*g.dart'
    